[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
  -D SUBSTRIDE_FW_VERSION=\"0.1.0\"
  -D SUBSTRIDE_HW_REVISION=\"v1-lab\"
  -D CORE_DEBUG_LEVEL=3
lib_deps =
  adafruit/Adafruit LSM6DS@^4.7.4
  adafruit/Adafruit BusIO@^1.16.2
  h2zero/NimBLE-Arduino@^1.4.2
  bblanchon/ArduinoJson@^7.2.1
